homeassistant:
  customize_domain:
    automation:
      initial_state: true
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.0/24
        - 192.168.4.0/24
        - 10.0.0.0/24
  packages: !include_dir_named packages

default_config:

config:

frontend:
  themes: !include_dir_merge_named themes

cloud:

alexa:
  filter:
    include_domains:
      - light
      - switch
      - cover
      - input_boolean
      - camera

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.4.0/24
    - 10.0.0.0/24

logbook: !include logbook.yaml
logger: !include logger.yaml
recorder: !include recorder.yaml

ffmpeg:

sun:
person:

zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 200
    icon: mdi:home
  - name: Work
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: 200
    icon: mdi:briefcase

sensor: !include_dir_merge_list sensor

script: !include_dir_merge_named script
scene: !include_dir_merge_named scene
template: !include_dir_merge_named template
input_boolean: !include_dir_merge_named input_boolean
light: !include_dir_merge_list light-groups

automation ui: !include automations.yaml
automation manual: !include_dir_merge_list automation

lovelace:
  dashboards:
    house-home:
      mode: yaml
      filename: dashboards/home.yaml
      title: Home
      icon: mdi:home-outline
      show_in_sidebar: true
    house-mobile:
      mode: yaml
      filename: dashboards/mobile.yaml
      title: Mobile
      icon: mdi:cellphone
      show_in_sidebar: true
    house-ops:
      mode: yaml
      filename: dashboards/ops.yaml
      title: Ops
      icon: mdi:server
      show_in_sidebar: true
      require_admin: true
