# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  ip_ban_enabled: false
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.4.0/24

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.4.0/24

frontend:
  themes: !include_dir_merge_named themes

ffmpeg:

sun:
person:

zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 200
    icon: mdi:home
  - name: Work
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: 200
    icon: mdi:briefcase

logger:
  default: error
  logs:
    homeassistant.components.image_processing: critical
    homeassistant.components.camera.generic: critical
    homeassistant.components.media_player: critical
    homeassistant.components.sensor.darksky: critical
    homeassistant.core: critical
    homeassistant.helpers.entity: critical
    homeassistant.components.http.ban: warning

tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
recorder: !include recorder.yaml
template: !include templates.yaml
input_boolean: !include input_boolean.yaml
sensor: !include sensors.yaml
