# Configure a default setup of Home Assistant (frontend, api, etc)

homeassistant:
  customize_domain:
    automation:
      initial_state: true
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.0/24
        - 192.168.4.0/24

default_config:

config:

frontend:
  themes: !include_dir_merge_named themes

cloud:

alexa:
  filter:
    include_domains:
      - light
      - switch
      - cover
      - input_boolean
      - camera

http:
  ip_ban_enabled: false
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.4.0/24

logbook: !include logbook.yaml
logger: !include logger.yaml
recorder: !include recorder.yaml

ffmpeg:

sun:
person:

zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 200
    icon: mdi:home
  - name: Work
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: 200
    icon: mdi:briefcase

tts:
  - platform: google_translate

automation manual: !include_dir_merge_list automation
automation ui: !include automations.yaml
script: !include_dir_merge_named script
scene: !include_dir_merge_named scene
template: !include_dir_merge_named template
input_boolean: !include_dir_merge_named input_boolean
sensor: !include_dir_merge_named sensor
light: !include_dir_merge_named light
